language: node_js
node_js:
- "7.5.0"

# Other settings
script:
- "gulp"
- "gulp test"

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"

install:
- "npm install"
- "npm install bower -g"
- "bower install"